version: '3'
services:
  splash:
    restart: always
    build: .
    environment:
      - NODE_ENV=production
    volumes:
        - shared-volume:/etc/mimo
    command: bash -c "cd /opt/app && grunt build && node ./dist/server/app.js"
    ports:
      - 8081:8080

volumes:
  shared-volume:
