version: 2
jobs:
  build:
    working_directory: ~/circulate
    docker:
      - image: circleci/node:6
    steps:
      - checkout

  docker:
    working_directory: ~/myapp
    docker:
      - image: alpine:latest
    steps:
      - run:
          name: Trigger Docker build
          command: apk add --no-cache curl && curl -XPOST https://registry.hub.docker.com/u/ohmimo/mimo-splash/trigger/${DOCKER_TOKEN}/

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - docker:
          requires:
            - build
          filters:
            branches:
              only:
                - master

