version: 2
jobs:
  build:
    working_directory: ~/circulate
    docker:
      - image: circleci/node:6
    steps:
      - checkout

      # - restore_cache:
      #     key: dependency-cache-{{ checksum "package.json" }}

      # - run:
      #     name: Install DEPS
      #     command: sudo npm install -g bower grunt grunt-cli grunt-karma karma --save-dev

      # - run:
      #     name: install-npm-wee
      #     command: ls && npm install

      # - run:
      #     name: Should test - please put me back
      #     command: echo 'Testing is for losers'

      # - save_cache:
      #     key: dependency-cache-{{ checksum "package.json" }}
      #     paths:
      #       - ./node_modules

  docker:
    working_directory: ~/myapp
    docker:
      - image: alpine:latest
    steps:
      - run:
          name: Trigger Docker build
          command: apk add --no-cache curl && curl -XPOST https://registry.hub.docker.com/u/ohmimo/mimo-splash/trigger/${DOCKER_TOKEN}/

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - beta
                - dev
      - docker:
          requires:
            - build
          filters:
            branches:
              only:
                - master

